### ISSUE TITLE
Process with an Id of 23376 is not running

### ISSUE THREAD

**Issue by nemeier** [bytefish/BlazorDataGridExample#1]
After downloading WideWorldImportes and BlazorDataGridExample i the the aboved error.
I get the error when starting BlazorDataGridExample

I use VS2022 fully patched

In the output windows the message is

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[23376] dotnet.exe' has exited with code 2147516566 (0x80008096).

Btw. WideWorldImportes don't have any problems

Any idea?

**Comment by bytefish** [comment]
Yes, I have an idea. I think the culprit is here:

* https://github.com/bytefish/BlazorDataGridExample/blob/5dc9befe912f842d6ff0027cd2e6217ba482ad76/BlazorDataGridExample/BlazorDataGridExample/BlazorDataGridExample.csproj#L29

Somehow if the .NET 7 Build and the DevServer do not match, it gives this strange error. Try to either update Visual Studio 2022 or try some lower version.

Before I have updated VS2022, it worked with Version 7.0.3 of the DevServer dependency.

**Comment by bytefish** [comment]
Please re-open for additional feedback.
